networks:
  kafka:
    name: kafka
services:
  vault:
    image: vault:1.6.2
    container_name: vault
    networks:
     - kafka
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    environment:
      VAULT_LOCAL_CONFIG: |
        {
          "storage": {
            "file": {"path": "/vault/file"}
          }, 
          "default_lease_ttl": "168h", 
          "max_lease_ttl": "720h",
          "listener": {
            "tcp": {
              "address": "0.0.0.0:8200",
              "tls_disable": true
            }
          },
          "ui": true
        }
      VAULT_ADDR: http://127.0.0.1:8200
    command:
      - "server"
    